### ISSUE TITLE
Error while runing project transfer learning

### ISSUE THREAD

**Issue by PanwarParamveer** [jwood803/MLNetExamples#10]
System.FormatException
  HResult=0x80131537
  Message=Tensorflow exception triggered while loading model.
  Source=Microsoft.ML.TensorFlow
  StackTrace:
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   at Microsoft.ML.TensorflowCatalog.LoadTensorFlowModel(ModelOperationsCatalog catalog, String modelLocation)
   at TransferLearning.Program.Main(String[] args) in X:\MLProject\MLNetExamples\TransferLearning\Program.cs:line 18

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by sefatanam** [comment]
Do you got any solution , because i'm getting this same error !

**Comment by jwood803** [comment]
This was raised in an [ML.NET issue](https://github.com/dotnet/machinelearning/issues/4679#issuecomment-608147488) as well. Try following those steps and if you still have issues just let me know.
